Repository zama-ai/evmos, pull requests merged in 2023-08, with the labels that each got.

#173 Fix developer image build
  .github/workflows/publish_developer_image.yml
  docker/Dockerfile.evmos-node.developer
  scripts/run_developer_image.sh
Labels: Type: CI, Type: Build

#175 Update to new version with tfhe decrypt
  Makefile
  README.md
  docker-compose/docker-compose.local.yml
  go.mod
Labels: Type: Build

#185 Update go eth 0.1.9
  Makefile
  go.mod
Labels: Type: Build, cla-signed

#188 Update developer image
  docker/Dockerfile.evmos-node.developer
Labels: cla-signed

#189 doc: add info related to release v0.1.8
  .env
  CHANGELOG.md
  README.md
  docker-compose/docker-compose.validator.yml
Labels: cla-signed
