Repository zama-ai/evmos, pull requests merged in 2023-09, with the labels that each got.

#191 feature: add rand() - publish v0.1.9-alpha
  .env
  .github/workflows/publish_developer_image.yml
  Makefile
  docker/Dockerfile.evmos-node.developer
  docker/Dockerfile.evmos-node.local
  go.mod
  scripts/run_tests.sh
Labels: Type: CI, Type: Build, cla-signed

#201 build(local): improve local build process and update README
  .env
  Makefile
  README.md
  docker/Dockerfile.evmos-node.developer
  docker/Dockerfile.evmos-node.local
  docker/Dockerfile.evmos-node.testnet
  go.mod
  scripts/prepare_volumes_from_fhe_tool_docker.sh
Labels: Type: Build, cla-signed

#206 doc(changelog): add info for v0.1.9
  CHANGELOG.md
  README.md
  docker-compose/docker-compose.validator.yml
Labels: cla-signed
